import {getItems, editExerciseBook, editAccessory, editBook, updateExerciseBook, updateBook, updateAccessory, saveExerciseBook, saveBook, saveAccessory } from "../controller/item.controller"
const express = require ("express")
const router = express.Router()
const auth = require('../controller/auth.controller')

router.post('/item/saveExerciseBook',auth,saveExerciseBook)
router.post('/item/saveBook',auth,saveBook)
router.post('/item/saveAccessory',auth,saveAccessory)
router.get('/item/listItems/:cat',auth,getItems)
router.get('/item/editExerciseBook/:id',auth,editExerciseBook)
router.get('/item/editBook/:id',auth,editBook)
router.get('/item/editAccessory/:id',auth,editAccessory)
router.put('/item/updateExerciseBook',auth,updateExerciseBook)
router.put('/item/updateBook',auth,updateBook)
router.put('/item/updateAccessory',auth,updateAccessory)

// router.post('/saveItem',saveItem)
// router.get('/listItems/:cat',getItems)
// router.get('/editExerciseBook/:id',editExerciseBook)
// router.get('/editBook/:id',editBook)
// router.get('/editAccessory/:id',editAccessory)
// router.put('/updateExerciseBook',updateExerciseBook)
// router.put('/updateBook',updateBook)
// router.put('/updateAccessory',updateAccessory)
module.exports = router